# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании / ИП')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('bank_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('contract_signed', models.BooleanField(default=False, verbose_name='Договор подписан')),
                ('contract_file', models.FileField(blank=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Номер договора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекламодатель',
                'verbose_name_plural': 'Рекламодатели',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок заказа')),
                ('description', models.TextField(verbose_name='Описание рекламы')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Бюджет (₽)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('active', 'Выполняется'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='advertisers.advertiser', verbose_name='Рекламодатель')),
                ('channels', models.ManyToManyField(to='channels.channel', verbose_name='Каналы размещения')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_order', to='billing.invoice', verbose_name='Счёт')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Рекламный заказ',
                'verbose_name_plural': 'Рекламные заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер акта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (₽)')),
                ('service_description', models.TextField(verbose_name='Описание услуг')),
                ('issued_at', models.DateField(verbose_name='Дата выдачи')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('pdf_file', models.FileField(blank=True, upload_to='acts/', verbose_name='PDF акта')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='advertisers.advertisingorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Акт выполненных работ',
                'verbose_name_plural': 'Акты выполненных работ',
                'ordering': ['-issued_at'],
            },
        ),
    ]
