# Generated by Django 4.2.29 on 2026-03-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingorder',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_order', to='content.post', verbose_name='Пост (автопубликация)'),
        ),
    ]
