# Generated by Django 4.2.29 on 2026-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_advertisingorder_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingorder',
            name='repeat_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='0 — один раз, иначе публиковать каждые N дней в период кампании', verbose_name='Повтор публикации (дней)'),
        ),
    ]
