# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово / фраза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_keywords', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='ParseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('dzen', 'Яндекс Дзен'), ('rss', 'RSS-лента')], max_length=20, verbose_name='Платформа')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source_id', models.CharField(help_text='Для TG: @channel_name, для VK: club12345, для RSS: URL ленты', max_length=255, verbose_name='ID / URL источника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_sources', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Источник парсинга',
                'verbose_name_plural': 'Источники парсинга',
            },
        ),
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('schedule_cron', models.CharField(default='0 */6 * * *', help_text='Например: 0 */6 * * * — каждые 6 часов', max_length=100, verbose_name='Cron расписание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('items_found_total', models.PositiveIntegerField(default=0, verbose_name='Найдено всего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(to='parsing.parsekeyword', verbose_name='Ключевые слова')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('sources', models.ManyToManyField(to='parsing.parsesource', verbose_name='Источники')),
            ],
            options={
                'verbose_name': 'Задача парсинга',
                'verbose_name_plural': 'Задачи парсинга',
            },
        ),
        migrations.AddField(
            model_name='parsekeyword',
            name='sources',
            field=models.ManyToManyField(related_name='keywords', to='parsing.parsesource', verbose_name='Источники'),
        ),
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Найденный текст')),
                ('original_url', models.URLField(blank=True, verbose_name='Ссылка на оригинал')),
                ('platform_id', models.CharField(blank=True, max_length=200, verbose_name='ID на платформе')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Использован'), ('ignored', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('ai_rewrite', models.TextField(blank=True, verbose_name='Версия от AI')),
                ('found_at', models.DateTimeField(auto_now_add=True, verbose_name='Найдено')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parsing.parsekeyword', verbose_name='Ключевое слово')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parsing.parsesource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Найденный материал',
                'verbose_name_plural': 'Найденные материалы',
                'ordering': ['-found_at'],
                'unique_together': {('source', 'platform_id')},
            },
        ),
        migrations.CreateModel(
            name='AIRewriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='Исходный текст')),
                ('result_text', models.TextField(blank=True, verbose_name='Результат AI')),
                ('prompt', models.TextField(blank=True, verbose_name='Кастомный промпт')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='Модель AI')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rewrite_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parsed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='parsing.parseditem', verbose_name='Источник (парсинг)')),
            ],
            options={
                'verbose_name': 'Задача AI рерайта',
                'verbose_name_plural': 'Задачи AI рерайта',
                'ordering': ['-created_at'],
            },
        ),
    ]
