# Generated by Django 4.2.29 on 2026-03-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_ads_fields'),
        ('parsing', '0003_backfill_channel_and_make_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsekeyword',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parse_keywords', to='channels.channel', verbose_name='Канал (куда парсим)'),
        ),
        migrations.AlterField(
            model_name='parsesource',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parse_sources', to='channels.channel', verbose_name='Канал (куда парсим)'),
        ),
    ]
