# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (₽)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('overdue', 'Просрочен')], default='draft', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('tbank_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID платежа TBank')),
                ('tbank_order_id', models.CharField(blank=True, max_length=200, verbose_name='Номер заказа TBank')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/', verbose_name='PDF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbank_payment_id', models.CharField(max_length=200, unique=True, verbose_name='ID платежа TBank')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (₽)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Ответ TBank')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=299.0, max_digits=10, verbose_name='Цена (₽/мес)')),
                ('channels_limit', models.PositiveIntegerField(default=1, verbose_name='Кол-во пабликов')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.JSONField(default=list, verbose_name='Возможности (список)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='channels.channel', verbose_name='Канал')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.payment', verbose_name='Платёж')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на канал',
                'verbose_name_plural': 'Подписки на каналы',
                'indexes': [models.Index(fields=['channel', 'is_active', 'ends_at'], name='billing_sub_channel_588390_idx'), models.Index(fields=['user', 'is_active'], name='billing_sub_user_id_f53484_idx')],
            },
        ),
    ]
