# Generated by Django 4.2.29 on 2026-03-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бота')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX')], max_length=20, verbose_name='Платформа')),
                ('bot_token_encrypted', models.TextField(verbose_name='Токен бота (зашифрован)')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Username / Имя бота')),
                ('admin_chat_id', models.CharField(blank=True, help_text='Chat ID группы или канала, куда будут приходить заявки с кнопками', max_length=100, verbose_name='ID чата для модерации (Telegram)')),
                ('group_id', models.CharField(blank=True, max_length=100, verbose_name='ID группы/сообщества (VK / MAX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('welcome_message', models.TextField(default='Привет! Отправьте мне вашу новость или предложение, и мы рассмотрим его для публикации.', verbose_name='Приветственное сообщение')),
                ('success_message', models.TextField(default='Спасибо! Ваша заявка #{tracking_id} принята и ожидает модерации.\n\nПроверить статус: /status', help_text='Используйте {tracking_id} — ID заявки', verbose_name='Сообщение об успешной отправке')),
                ('approved_message', models.TextField(default='Ваша заявка #{tracking_id} одобрена и будет опубликована! Спасибо за вклад.', help_text='Используйте {tracking_id}', verbose_name='Сообщение об одобрении')),
                ('rejected_message', models.TextField(default='Ваша заявка #{tracking_id} не прошла модерацию.\nПричина: {reason}', help_text='Используйте {tracking_id} и {reason}', verbose_name='Сообщение об отклонении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бот предложки',
                'verbose_name_plural': 'Боты предложки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('platform_username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Отображаемое имя')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Всего предложений')),
                ('approved', models.PositiveIntegerField(default=0, verbose_name='Одобрено')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='Отклонено')),
                ('pending', models.PositiveIntegerField(default=0, verbose_name='На модерации')),
                ('published', models.PositiveIntegerField(default=0, verbose_name='Опубликовано')),
                ('last_submission', models.DateTimeField(blank=True, null=True, verbose_name='Последняя заявка')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='bots.suggestionbot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
                'ordering': ['-approved', '-total'],
                'unique_together': {('bot', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID отслеживания')),
                ('platform_user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('platform_username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('platform_first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('platform_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('mixed', 'Смешанное')], max_length=20, verbose_name='Тип контента')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('media_file_ids', models.JSONField(default=list, verbose_name='ID медиафайлов')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные от платформы')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('published', 'Опубликовано')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Внутренняя заметка модератора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='bots.suggestionbot', verbose_name='Бот')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['bot', 'status'], name='bots_sugges_bot_id_38207f_idx'), models.Index(fields=['platform_user_id', 'bot'], name='bots_sugges_platfor_71da2b_idx')],
            },
        ),
    ]
