# Generated by Django 4.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_globalapikeys_parse_media_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalapikeys',
            name='parse_media_disk_quota_bytes',
            field=models.PositiveBigIntegerField(
                default=5368709120,
                validators=[django.core.validators.MaxValueValidator(1099511627776)],
                verbose_name='PARSE_MEDIA_DISK_QUOTA_BYTES',
                help_text='Суммарный лимит байт для media/parsed_items + media/imports/tg_to_max. 0 — квота отключена. post_media не входит.',
            ),
        ),
    ]
