# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email приглашённого')),
                ('role', models.CharField(choices=[('assistant_admin', 'Помощник-администратор'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assistant_admin', 'Помощник-администратор'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('can_publish', models.BooleanField(default=True, verbose_name='Может публиковать')),
                ('can_moderate', models.BooleanField(default=True, verbose_name='Может модерировать предложки')),
                ('can_view_stats', models.BooleanField(default=True, verbose_name='Видит статистику')),
                ('can_manage_bots', models.BooleanField(default=False, verbose_name='Управляет ботами')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Вступил')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('channels', models.ManyToManyField(blank=True, to='channels.channel', verbose_name='Доступные каналы')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'unique_together': {('owner', 'member')},
            },
        ),
    ]
