# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('forwards', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_stat_snapshots', to='channels.channel', verbose_name='Канал')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Снимок статистики поста',
                'verbose_name_plural': 'Снимки статистики постов',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['post', 'recorded_at'], name='stats_posts_post_id_3a27c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('reactions', models.PositiveIntegerField(default=0, verbose_name='Реакций')),
                ('forwards', models.PositiveIntegerField(default=0, verbose_name='Репостов')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Комментариев')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_stats', to='channels.channel', verbose_name='Канал')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Статистика поста',
                'verbose_name_plural': 'Статистика постов',
                'unique_together': {('post', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='MarketingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('avg_reach', models.FloatField(default=0.0, verbose_name='Средний охват на пост')),
                ('avg_er', models.FloatField(default=0.0, verbose_name='Средний ER (%)')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_posts', models.PositiveIntegerField(default=0, verbose_name='Постов за период')),
                ('total_reactions', models.PositiveIntegerField(default=0, verbose_name='Всего реакций')),
                ('subscribers_start', models.PositiveIntegerField(default=0, verbose_name='Подписчиков в начале')),
                ('subscribers_end', models.PositiveIntegerField(default=0, verbose_name='Подписчиков в конце')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reports', to='channels.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Маркетинговый отчёт',
                'verbose_name_plural': 'Маркетинговые отчёты',
                'unique_together': {('channel', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ChannelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('subscribers', models.PositiveIntegerField(default=0, verbose_name='Подписчиков')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотров за день')),
                ('er', models.FloatField(default=0.0, verbose_name='ER (вовлечённость %)')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Постов за день')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='channels.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Статистика канала',
                'verbose_name_plural': 'Статистика каналов',
                'ordering': ['-date'],
                'unique_together': {('channel', 'date')},
            },
        ),
    ]
