# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название канала')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('max', 'MAX'), ('instagram', 'Instagram')], max_length=20, verbose_name='Платформа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channel_avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('tg_chat_id', models.CharField(blank=True, max_length=100, verbose_name='TG Chat ID / @username')),
                ('tg_bot_token_enc', models.TextField(blank=True, verbose_name='TG токен бота (зашифр.)')),
                ('vk_group_id', models.CharField(blank=True, max_length=50, verbose_name='VK Group ID')),
                ('vk_access_token_enc', models.TextField(blank=True, verbose_name='VK Access Token (зашифр.)')),
                ('max_channel_id', models.CharField(blank=True, max_length=100, verbose_name='MAX Channel ID')),
                ('max_bot_token_enc', models.TextField(blank=True, verbose_name='MAX токен бота (зашифр.)')),
                ('ig_account_id', models.CharField(blank=True, max_length=100, verbose_name='Instagram Account ID')),
                ('ig_access_token_enc', models.TextField(blank=True, verbose_name='Instagram Access Token (зашифр.)')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='Подписчиков')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['-created_at'],
            },
        ),
    ]
