# Generated by Django 4.2.29 on 2026-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='footer',
            field=models.TextField(blank=True, help_text='Добавляется к каждому посту (кроме рекламных с ОРД меткой). Поддерживает эмодзи и переносы строк.', verbose_name='Подпись канала'),
        ),
    ]
