# Generated by Django 4.2.29 on 2026-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_add_channel_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='footer',
        ),
        migrations.AddField(
            model_name='channel',
            name='max_footer',
            field=models.TextField(blank=True, help_text='HTML-разметка: <b>жирный</b>, <i>курсив</i>, <a href="url">ссылка</a>', verbose_name='Подпись MAX'),
        ),
        migrations.AddField(
            model_name='channel',
            name='tg_footer',
            field=models.TextField(blank=True, help_text='HTML-разметка: <b>жирный</b>, <i>курсив</i>, <a href="url">ссылка</a>, <blockquote>цитата</blockquote>', verbose_name='Подпись Telegram'),
        ),
        migrations.AddField(
            model_name='channel',
            name='vk_footer',
            field=models.TextField(blank=True, help_text='Обычный текст. Ссылки: [club123|Название] или https://...', verbose_name='Подпись ВКонтакте'),
        ),
    ]
