# Generated by Django 4.2.29 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_per_platform_footers"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="ad_enabled",
            field=models.BooleanField(default=False, verbose_name="Принимает рекламу"),
        ),
        migrations.AddField(
            model_name="channel",
            name="ad_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Используется в кабинете рекламодателя для расчёта бюджета",
                max_digits=12,
                verbose_name="Цена за 1 размещение (₽)",
            ),
        ),
    ]

