# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирован'), ('publishing', 'Публикуется'), ('published', 'Опубликован'), ('failed', 'Ошибка')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запланировано на')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано в')),
                ('repeat_enabled', models.BooleanField(default=False, verbose_name='Повторять публикацию')),
                ('repeat_type', models.CharField(choices=[('none', 'Без повтора'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('interval', 'Через N дней')], default='none', max_length=20, verbose_name='Тип повтора')),
                ('repeat_interval_days', models.PositiveIntegerField(default=3, verbose_name='Интервал повтора (дней)')),
                ('repeat_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во повторов (0=∞)')),
                ('repeat_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания повтора')),
                ('has_premium_emoji', models.BooleanField(default=False, verbose_name='Содержит TG Premium Emoji')),
                ('tg_entities', models.JSONField(default=list, verbose_name='TG entities (premium emoji)')),
                ('ord_label', models.CharField(blank=True, max_length=500, verbose_name='Текст метки ОРД (Реклама)')),
                ('ord_token', models.CharField(blank=True, max_length=200, verbose_name='Токен ОРД')),
                ('disable_notification', models.BooleanField(default=False, verbose_name='Тихая публикация (TG)')),
                ('pin_message', models.BooleanField(default=False, verbose_name='Закрепить сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('channels', models.ManyToManyField(related_name='posts', to='channels.channel', verbose_name='Каналы для публикации')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bots.suggestion', verbose_name='Источник (предложка)')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('fail', 'Ошибка')], max_length=10, verbose_name='Статус')),
                ('platform_message_id', models.CharField(blank=True, max_length=200, verbose_name='ID сообщения на платформе')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_results', to='channels.channel', verbose_name='Канал')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_results', to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Результат публикации',
                'verbose_name_plural': 'Результаты публикации',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('text', models.TextField(verbose_name='Текст шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channels', models.ManyToManyField(blank=True, to='channels.channel', verbose_name='Каналы по умолчанию')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон поста',
                'verbose_name_plural': 'Шаблоны постов',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/%Y/%m/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], max_length=20, verbose_name='Тип')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Медиафайл поста',
                'verbose_name_plural': 'Медиафайлы постов',
                'ordering': ['order'],
            },
        ),
    ]
