# Generated by Django 4.2.29 on 2026-03-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('content', '0001_initial'),
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_token', models.CharField(blank=True, max_length=500, verbose_name='Токен маркировки ОРД')),
                ('ord_id', models.CharField(blank=True, max_length=200, verbose_name='ID в реестре ОРД')),
                ('label_text', models.CharField(default='Реклама', max_length=500, verbose_name='Текст метки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('registered', 'Зарегистрирован'), ('error', 'Ошибка'), ('expired', 'Истёк')], default='pending', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Зарегистрировано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Ответ ВК ОРД API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisers.advertiser', verbose_name='Рекламодатель')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_registrations', to='channels.channel', verbose_name='Канал')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_registrations', to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'ОРД регистрация',
                'verbose_name_plural': 'ОРД регистрации',
                'ordering': ['-created_at'],
            },
        ),
    ]
